### ISSUE TITLE
Bug in ad-hoc/bridge test

### ISSUE THREAD

**Issue by cdmcdonell** [typetools/annotation-tools#131] opened 2016-12-15 14:59 UTC
I am building jsr308 + annotation tools + checker framework with Oracle jdk 1.8.0_112. After building jsr308-langtools, running ant in annotation-tools fails in annotation-file-utilities/tests/ad-hoc/bridge with the error: "Unable to find class A." Adding "." to CLASSPATH before running extract-annotations fixes this. I've attached a diff.
[Makefile.txt](https://github.com/typetools/annotation-tools/files/654949/Makefile.txt)

**Comment by mernst** [comment] 2016-12-15 16:33
Thanks for the bug report, and I'm sorry you are having trouble.
I'm not able to reproduce the problem.
What is your CLASSPATH when you run `ant` in `annotation-tools/`?  If you unset the CLASSPATH environment variable, do you still get the problem?

**Comment by mernst** [comment] 2016-12-15 16:37
This looks safe, so I went ahead and committed your proposed change.  Thanks!

**Closed** 2016-12-15 16:36 UTC

**Comment by cdmcdonell** [comment] 2016-12-15 16:44
Thank you, but I believe you nailed the problem. My CLASSPATH was set to something already in that shell. I unset it, and that seems to have fixed the problem. Thank you very much!

**Comment by mernst** [comment] 2016-12-15 16:54
It's a general recommendation not to set one's CLASSPATH, but nonetheless our test suite should pass when one violates that recommendation -- and thanks to you, now it does.
